title: byro
email: rixx-byro@rixx.de
description: >-
  byro is a free, open-source membership management tool.
baseurl: "" # subpath
url: "https://byro.cloud"
twitter_username: byrocloud
github_username:  byro

# Build settings
markdown: kramdown

navigation:
  - title: Features
    title_de: Features
    url: /features
  - title: Hosting
    title_de: Hosting
    url: /hosting
  - title: Documentation
    title_de: Dokumentation
    url: https://byro.readthedocs.io/en/latest/
  - title: Source
    title_de: Quelltext
    url: https://github.com/byro/byro
